<?php

return [
    'sign_in' => 'Sign In',
    'go_to_login' => 'Go to Login',
    'failed' => 'No account matching those credentials could be found.',

    'forgot_password' => [
        'label' => 'Forgot Password?',
        'label_help' => 'Enter your account email address to receive instructions on resetting your password.',
        'button' => 'Recover Account',
    ],

    'reset_password' => [
        'button' => 'Reset and Sign In',
    ],

    'two_factor' => [
        'label' => '2-Factor Token',
        'label_help' => 'This account requires a second layer of authentication in order to continue. Please enter the code generated by your device to complete this login.',
        'checkpoint_failed' => 'The two-factor authentication token was invalid.',
    ],

    'sso' => [
        'google' => [
            'disabled' => 'Google sign-in is not enabled.',
            'state' => 'The sign-in session expired, please try again.',
            'unverified' => 'Your Google account email is not verified.',
            'domain' => 'Only Google Workspace accounts from an allowed domain can sign in to this panel.',
            'no-account' => 'There is no panel account for this Google account. Ask an administrator.',
            'already-linked' => 'This Google account is already linked to another user.',
            'linked' => 'Your Google account has been linked.',
        ],
    ],

    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'password_requirements' => 'Password must be at least 8 characters in length and should be unique to this site.',
    '2fa_must_be_enabled' => 'The administrator has required that 2-Factor Authentication be enabled for your account in order to use the Panel.',
];
