<?php

namespace Pterodactyl\Models;

use Ramsey\Uuid\Uuid;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Builder;
use Pterodactyl\Services\NodeWatcher\DeliveryResult;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @property int $id
 * @property string $uuid
 * @property string $name
 * @property string $url
 * @property string $secret
 * @property string[] $events
 * @property int[]|null $node_ids
 * @property string|null $body_template
 * @property bool $enabled
 * @property \Carbon\Carbon|null $last_delivery_at
 * @property int|null $last_status
 * @property string|null $last_error
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class NodeWatcherWebhook extends Model
{
    /** @use HasFactory<\Database\Factories\NodeWatcherWebhookFactory> */
    use HasFactory;

    public const RESOURCE_NAME = 'node_watcher_webhook';

    /**
     * Published when the overall pressure level of a node changes, including the
     * change back to "ok".
     */
    public const EVENT_PRESSURE = 'host.pressure';

    /**
     * Published on the configured interval with the current utilization of a node.
     */
    public const EVENT_HEARTBEAT = 'host.heartbeat';

    /**
     * Published when the Panel fails to reach a node several times in a row. A
     * subscription to this event also receives the matching "node.reachable" event.
     */
    public const EVENT_UNREACHABLE = 'node.unreachable';
    public const EVENT_REACHABLE = 'node.reachable';

    /**
     * Sent by the "Test" button in the admin area. Every webhook receives it.
     */
    public const EVENT_PING = 'ping';

    /**
     * The events a webhook can subscribe to.
     */
    public const EVENTS = [
        self::EVENT_PRESSURE,
        self::EVENT_HEARTBEAT,
        self::EVENT_UNREACHABLE,
    ];

    /**
     * Every event a webhook can receive, in the order the admin area lists them.
     * Each one has a sample payload for validating and previewing templates.
     */
    public const SAMPLE_EVENTS = [
        self::EVENT_PRESSURE,
        self::EVENT_HEARTBEAT,
        self::EVENT_UNREACHABLE,
        self::EVENT_REACHABLE,
        self::EVENT_PING,
    ];

    /**
     * What each subscription means, for the admin area.
     */
    public const EVENT_DESCRIPTIONS = [
        self::EVENT_PRESSURE => 'The pressure level of a node changed (ok, warning or critical).',
        self::EVENT_HEARTBEAT => 'A utilization snapshot of every node, on the heartbeat interval.',
        self::EVENT_UNREACHABLE => 'A node failed three heartbeats in a row, and again when it is back.',
    ];

    protected $table = 'node_watcher_webhooks';

    protected $fillable = [
        'name',
        'url',
        'events',
        'node_ids',
        'body_template',
        'enabled',
    ];

    protected $casts = [
        'secret' => 'encrypted',
        'events' => 'array',
        'node_ids' => 'array',
        'enabled' => 'bool',
        'last_delivery_at' => 'datetime',
        'last_status' => 'int',
    ];

    protected $attributes = [
        'enabled' => true,
    ];

    public static array $validationRules = [
        'uuid' => 'required|uuid',
        'name' => 'required|string|max:100',
        'url' => 'required|string|url:http,https|max:2000',
        'secret' => 'required|string',
        'events' => 'required|array|min:1',
        'events.*' => 'string|in:host.pressure,host.heartbeat,node.unreachable',
        'node_ids' => 'nullable|array',
        'node_ids.*' => 'integer|exists:nodes,id',
        'body_template' => 'nullable|string|max:65535',
        'enabled' => 'boolean',
    ];

    /**
     * The identifier and the secret are generated by the Panel, never supplied by
     * a form. They are filled in before the base model validates the record.
     */
    protected static function boot()
    {
        static::saving(function (self $webhook) {
            $webhook->uuid = $webhook->uuid ?: Uuid::uuid4()->toString();
            if (empty($webhook->getAttributes()['secret'])) {
                $webhook->secret = static::generateSecret();
            }
        });

        parent::boot();
    }

    /**
     * Generates a new shared secret. The receiver uses it to verify the HMAC
     * signature of every delivery.
     */
    public static function generateSecret(): string
    {
        return bin2hex(random_bytes(32));
    }

    /**
     * Maps an event to the subscription that receives it. Recovery events are
     * delivered to whoever asked for the failure they resolve.
     */
    public static function subscriptionFor(string $event): string
    {
        return $event === self::EVENT_REACHABLE ? self::EVENT_UNREACHABLE : $event;
    }

    /**
     * @param Builder<self> $query
     */
    public function scopeEnabled(Builder $query): void
    {
        $query->where('enabled', true);
    }

    /**
     * Determines if this webhook should receive the given event for the given node.
     * The ping event ignores the subscriptions so that the "Test" button always works.
     */
    public function isSubscribedTo(string $event, ?Node $node = null): bool
    {
        if ($event === self::EVENT_PING) {
            return true;
        }

        if (!in_array(self::subscriptionFor($event), $this->events ?? [], true)) {
            return false;
        }

        if (is_null($node) || empty($this->node_ids)) {
            return true;
        }

        return in_array($node->id, $this->node_ids, true);
    }

    /**
     * Stores the outcome of the most recent delivery attempt on the webhook.
     */
    public function recordDelivery(DeliveryResult $result): void
    {
        $this->forceFill([
            'last_delivery_at' => now(),
            'last_status' => $result->status,
            'last_error' => is_null($result->error) ? null : Str::limit($result->error, 250, '…'),
        ])->save();
    }
}
